# Generated by Django 2.1.4 on 2018-12-05 03:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=40)),
                ('lattitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('room_type', models.CharField(max_length=30)),
                ('furnished', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('furnished', models.BooleanField()),
                ('num_pictures', models.PositiveSmallIntegerField()),
                ('rating', models.DecimalField(decimal_places=3, max_digits=5)),
                ('date_listed', models.DateField()),
                ('timestamp_logged', models.DateTimeField(default=django.utils.timezone.now)),
                ('fk_address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property_safe.Address')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='fk_property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_safe.Property'),
        ),
    ]
