# Generated by Django 2.1.4 on 2018-12-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_safe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
