# Generated by Django 2.1.4 on 2018-12-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_safe', '0002_auto_20181205_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='fk_property_id',
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ManyToManyField(to='property_safe.Image'),
        ),
    ]
