# Generated by Django 2.1.4 on 2018-12-09 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_safe', '0003_auto_20181205_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
