# Generated by Django 2.1.4 on 2018-12-09 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_safe', '0004_auto_20181209_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='latitude',
            new_name='lattitude',
        ),
    ]
